import { useMemo, useState } from 'react';
import { FileText, Plus, Sparkles, X, Download, FileDown, Printer, Copy, Check } from 'lucide-react';
import { useQueryClient } from '@tanstack/react-query';
import { getListActivityQueryKey, getListDeadlinesQueryKey, useDraftComplianceReport, useListDeadlines, type Deadline } from '@workspace/api-client-react';
import { Button, DeadlineRow, Drawer, EmptyBlock, ErrorBlock, LoadingBlock, SectionHeading, StatusPill } from '@/components/guardian-ui';
import { apiRequest, getSubmittedDeadlineIds, markDeadlineSubmittedLocal, isDeadlineSubmittedLocal, addLocalActivity } from '@/lib/api';
import { useAuth, formatDisplayName } from '@/context/auth-context';

export default function Compliance() {
  const queryClient = useQueryClient();
  const query = useListDeadlines();
  const { user } = useAuth();
  const [submittedIds, setSubmittedIds] = useState<Set<number>>(getSubmittedDeadlineIds);
  const draftMutation = useDraftComplianceReport();
  const [draft, setDraft] = useState<{ id: number; deadlineId: number; title: string; status: string; body: string } | null>(null);
  const [draftError, setDraftError] = useState('');
  const [showAddModal, setShowAddModal] = useState(false);
  const [copied, setCopied] = useState(false);

  // New Deadline form state
  const [newTitle, setNewTitle] = useState('');
  const [newType, setNewType] = useState('Regulatory filing');
  const [newDays, setNewDays] = useState('21');
  const [newProgress, setNewProgress] = useState('25');
  const [isAdding, setIsAdding] = useState(false);

  const rawDeadlines = Array.isArray(query.data) ? query.data : [];
  const deadlines = useMemo(() => {
    return rawDeadlines.map((d: Deadline) => {
      const isSub =
        (d.progress ?? 0) >= 100 ||
        (d.status as string) === 'clear' ||
        (d.status as string) === 'submitted' ||
        submittedIds.has(d.id) ||
        isDeadlineSubmittedLocal(d.id);
      if (isSub) {
        return {
          ...d,
          status: 'clear' as const,
          progress: 100,
        };
      }
      return d;
    });
  }, [rawDeadlines, submittedIds]);
  const attention = deadlines.filter((deadline: Deadline) => deadline.status === 'attention').length;

  const draftReport = (id: number) => {
    setDraftError('');
    draftMutation.mutate({ id }, {
      onSuccess: (result: { id: number; deadlineId: number; title: string; status: string; body: string }) => {
        setDraft(result);
        void Promise.all([
          queryClient.invalidateQueries({ queryKey: getListDeadlinesQueryKey() }),
          queryClient.invalidateQueries({ queryKey: getListActivityQueryKey() }),
        ]);
      },
      onError: () => setDraftError('The report could not be drafted. Try again in a moment.'),
    });
  };

  const handleDownload = (format: 'md' | 'txt' = 'md') => {
    if (!draft) return;
    const cleanTitle = draft.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
    const filename = `${cleanTitle || 'compliance-report-draft'}.${format}`;
    const blob = new Blob([draft.body], {
      type: format === 'md' ? 'text/markdown;charset=utf-8' : 'text/plain;charset=utf-8',
    });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleCopy = async () => {
    if (!draft) return;
    try {
      await navigator.clipboard.writeText(draft.body);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Graceful fallback
    }
  };

  const handlePrintPdf = () => {
    if (!draft) return;
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    printWindow.document.write(`<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${draft.title}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; padding: 40px; color: #111; line-height: 1.6; }
    h1 { color: #0f172a; font-size: 24px; margin-bottom: 8px; border-bottom: 2px solid #0f172a; padding-bottom: 8px; }
    .meta { font-size: 12px; color: #64748b; margin-bottom: 24px; padding-bottom: 12px; border-bottom: 1px solid #e2e8f0; }
    pre { background: #f8fafc; padding: 18px; border-radius: 8px; font-size: 13px; border: 1px solid #e2e8f0; white-space: pre-wrap; word-wrap: break-word; font-family: inherit; }
    @media print {
      body { padding: 0; }
      pre { border: none; background: transparent; padding: 0; }
    }
  </style>
</head>
<body>
  <h1>${draft.title}</h1>
  <div class="meta">Deadline ID: #${draft.deadlineId} | Generated by Grant Guardian | Manual PI Signoff Enforced</div>
  <pre>${draft.body}</pre>
</body>
</html>`);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 250);
  };

  const handleCreateDeadline = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTitle.trim()) return;
    setIsAdding(true);
    try {
      const days = parseInt(newDays, 10) || 14;
      const dueDate = new Date(Date.now() + days * 86400000).toISOString();
      const res = await apiRequest('/api/guardian/deadlines', {
        method: 'POST',
        body: JSON.stringify({
          title: newTitle.trim(),
          type: newType,
          dueDate,
          progress: parseInt(newProgress, 10) || 10,
        }),
      });
      if (res.ok) {
        setNewTitle('');
        setShowAddModal(false);
        await Promise.all([
          queryClient.invalidateQueries({ queryKey: getListDeadlinesQueryKey() }),
          queryClient.invalidateQueries({ queryKey: getListActivityQueryKey() }),
        ]);
      }
    } catch {
      // error handled gracefully
    } finally {
      setIsAdding(false);
    }
  };

  const handleMarkSubmitted = async (id: number) => {
    // 1. Immediately record in localStorage so state is persisted across pages & reloads
    markDeadlineSubmittedLocal(id);
    setSubmittedIds(new Set(getSubmittedDeadlineIds()));

    // 2. Add local activity log so /activity immediately has this milestone
    const target = deadlines.find((d: Deadline) => d.id === id);
    const title = target?.title || 'Compliance milestone';
    const ownerName = formatDisplayName(user);
    addLocalActivity({
      title: `Compliance milestone filed externally: ${title}`,
      description: `Marked officially submitted by PI (${ownerName}) to external sponsor portal. Progress registered at 100%.`,
      kind: 'clear',
      tone: 'success',
    });

    // 3. Optimistically update React Query cache for instant zero-latency UI update
    queryClient.setQueryData(getListDeadlinesQueryKey(), (old: Deadline[] | undefined) => {
      if (!Array.isArray(old)) return old;
      return old.map((d) =>
        d.id === id ? { ...d, status: 'clear' as const, progress: 100 } : d
      );
    });

    // 4. Send persistent PATCH to server with active user credentials
    try {
      await apiRequest(`/api/guardian/deadlines/${id}`, {
        method: 'PATCH',
        body: JSON.stringify({
          status: 'on_track',
          progress: 100,
          submitted: true,
        }),
      });

      await Promise.all([
        queryClient.invalidateQueries({ queryKey: getListDeadlinesQueryKey() }),
        queryClient.invalidateQueries({ queryKey: getListActivityQueryKey() }),
      ]);
    } catch {
      // LocalStorage and optimistic cache preserve state
    }
  };

  return (
    <div className="gg-stagger space-y-6">
      <SectionHeading
        eyebrow="Compliance desk"
        title="Keep the paperwork moving."
        description="Guardian tracks the dates that can quietly derail a grant. When a deadline needs shape, it can make the first draft for you."
        action={
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-2 rounded-lg border border-[hsl(var(--border))] bg-[hsl(var(--card))] px-3 py-2 text-[11px] text-[hsl(var(--muted-foreground))]">
              <span className="size-2 rounded-full bg-emerald-500" />
              {attention ? `${attention} deadline${attention === 1 ? '' : 's'} need attention` : 'All deadlines on track'}
            </div>
            <button
              type="button"
              onClick={() => setShowAddModal(true)}
              className="inline-flex items-center gap-1.5 rounded-lg bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))] px-3.5 py-2 text-xs font-semibold hover:opacity-90 transition-opacity shadow-2xs cursor-pointer"
              data-testid="button-add-deadline"
            >
              <Plus size={14} />
              <span>Track New Deadline</span>
            </button>
          </div>
        }
      />

      {/* Compliance Metrics Overview - Clean theme cards blending with background */}
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <div className="rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-4 shadow-2xs">
          <div className="gg-mono text-[9px] uppercase tracking-wider text-[hsl(var(--muted-foreground))]">
            Total Tracked
          </div>
          <div className="mt-2 text-[24px] font-extrabold text-[hsl(var(--foreground))]">{deadlines.length}</div>
          <div className="mt-1 text-[10px] text-[hsl(var(--muted-foreground))]">Active grant deadlines</div>
        </div>
        <div className="rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-4 shadow-2xs">
          <div className="gg-mono text-[9px] uppercase tracking-wider text-[hsl(var(--muted-foreground))] font-semibold">
            Needs Attention
          </div>
          <div className="mt-2 text-[24px] font-extrabold text-[hsl(var(--foreground))]">
            {deadlines.filter((d: Deadline) => d.status === 'attention').length}
          </div>
          <div className="mt-1 text-[10px] text-[hsl(var(--muted-foreground))]">&lt;14d runway &amp; &lt;80% prep</div>
        </div>
        <div className="rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-4 shadow-2xs">
          <div className="gg-mono text-[9px] uppercase tracking-wider text-[hsl(var(--muted-foreground))] font-semibold">
            Due Soon
          </div>
          <div className="mt-2 text-[24px] font-extrabold text-[hsl(var(--foreground))]">
            {deadlines.filter((d: Deadline) => d.status === 'due_soon').length}
          </div>
          <div className="mt-1 text-[10px] text-[hsl(var(--muted-foreground))]">11–21 days preparation window</div>
        </div>
        <div className="rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-4 shadow-2xs">
          <div className="gg-mono text-[9px] uppercase tracking-wider text-[hsl(var(--muted-foreground))] font-semibold">
            On Track / Clear
          </div>
          <div className="mt-2 text-[24px] font-extrabold text-[hsl(var(--foreground))]">
            {deadlines.filter((d: Deadline) => d.status === 'on_track' || (d.status as string) === 'submitted').length}
          </div>
          <div className="mt-1 text-[10px] text-[hsl(var(--muted-foreground))]">Adequate milestone runway</div>
        </div>
      </div>

      {draftError && (
        <div
          className="mb-5 flex items-center justify-between rounded-lg border border-[hsl(var(--destructive)/.25)] bg-[hsl(var(--destructive)/.06)] px-4 py-3 text-[11px] text-[hsl(var(--destructive))]"
          data-testid="status-draft-error"
        >
          {draftError}
          <button
            type="button"
            onClick={() => setDraftError('')}
            aria-label="Dismiss error"
            data-testid="button-dismiss-draft-error"
          >
            <X size={14} />
          </button>
        </div>
      )}
      {query.isError ? (
        <ErrorBlock onRetry={() => void query.refetch()} />
      ) : query.isLoading ? (
        <LoadingBlock lines={7} />
      ) : deadlines.length === 0 ? (
        <EmptyBlock
          title="No deadlines in view"
          detail="When compliance dates are connected, Guardian will keep their distance and timeline here."
        />
      ) : (
        <div className="grid gap-5 lg:grid-cols-[1fr_330px]">
          <section
            className="overflow-hidden rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))]"
            data-testid="section-deadline-register"
          >
            <div className="flex items-center justify-between border-b border-[hsl(var(--border))] px-5 py-4">
              <div>
                <div className="gg-mono text-[9px] uppercase tracking-[.17em] text-[hsl(var(--muted-foreground))]">
                  Active register
                </div>
                <h2 className="mt-1 text-[15px] font-bold">{deadlines.length} tracked dates</h2>
              </div>
              <div className="gg-mono text-[9px] uppercase tracking-[.12em] text-[hsl(var(--muted-foreground))]">
                Sorted by urgency
              </div>
            </div>
            {deadlines
              .slice()
              .sort((a: Deadline, b: Deadline) => a.daysLeft - b.daysLeft)
              .map((deadline: Deadline) => (
                <DeadlineRow
                  key={deadline.id}
                  deadline={deadline}
                  onDraft={() => draftReport(deadline.id)}
                  onMarkSubmitted={() => handleMarkSubmitted(deadline.id)}
                />
              ))}
          </section>
          <aside
            className="h-fit rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5 text-[hsl(var(--foreground))] shadow-xs space-y-4"
            data-testid="card-compliance-note"
          >
            <div className="flex size-9 items-center justify-center rounded-lg bg-[hsl(var(--muted))] text-[hsl(var(--foreground))]">
              <FileText size={17} />
            </div>
            <div className="gg-serif text-[24px] leading-[1.05]">
              A good first draft
              <br />
              <em>buys back a day.</em>
            </div>
            <p className="text-[11px] leading-relaxed text-[hsl(var(--muted-foreground))]">
              Select “Draft report” on an upcoming deadline. Guardian will use the deadline context to prepare a
              reviewable starting point — never an external submission.
            </p>
            <div className="border-t border-[hsl(var(--border))] pt-4 text-[10px] text-[hsl(var(--muted-foreground))]">
              <div className="flex justify-between items-center">
                <span>Drafts remain private</span>
                <span className="rounded bg-[hsl(var(--muted))] px-2 py-0.5 font-mono text-[9px] font-bold text-[hsl(var(--muted-foreground))]">
                  LOCAL ONLY
                </span>
              </div>
            </div>
          </aside>
        </div>
      )}

      {/* Add Deadline Modal */}
      {showAddModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 backdrop-blur-xs p-4">
          <div className="w-full max-w-md rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-6 shadow-xl space-y-4">
            <div className="flex items-center justify-between border-b border-[hsl(var(--border))] pb-3">
              <h3 className="text-[14px] font-bold text-[hsl(var(--foreground))]">Track New Compliance Deadline</h3>
              <button
                type="button"
                onClick={() => setShowAddModal(false)}
                className="text-[hsl(var(--muted-foreground))] hover:text-[hsl(var(--foreground))]"
              >
                <X size={16} />
              </button>
            </div>

            <form onSubmit={handleCreateDeadline} className="space-y-3.5">
              <div>
                <label className="block text-[11px] font-bold text-[hsl(var(--foreground))] mb-1">
                  Milestone / Requirement Title
                </label>
                <input
                  type="text"
                  required
                  placeholder="e.g. NIH Conflict of Interest Disclosure or IRB Modification"
                  value={newTitle}
                  onChange={(e) => setNewTitle(e.target.value)}
                  className="w-full rounded-lg border border-[hsl(var(--border))] bg-[hsl(var(--background))] px-3 py-2 text-xs text-[hsl(var(--foreground))] focus:outline-none focus:ring-1 focus:ring-slate-400"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-[11px] font-bold text-[hsl(var(--foreground))] mb-1">
                    Agency / Type
                  </label>
                  <select
                    value={newType}
                    onChange={(e) => setNewType(e.target.value)}
                    className="w-full rounded-lg border border-[hsl(var(--border))] bg-[hsl(var(--background))] px-3 py-2 text-xs text-[hsl(var(--foreground))] focus:outline-none"
                  >
                    <option value="IRB renewal">IRB renewal</option>
                    <option value="Funding report">Funding report</option>
                    <option value="Data management">Data management</option>
                    <option value="Biosafety audit">Biosafety audit</option>
                    <option value="Material transfer">Material transfer</option>
                    <option value="Ethics disclosure">Ethics disclosure</option>
                    <option value="Export control">Export control</option>
                    <option value="Regulatory filing">Regulatory filing</option>
                  </select>
                </div>

                <div>
                  <label className="block text-[11px] font-bold text-[hsl(var(--foreground))] mb-1">
                    Days until due
                  </label>
                  <input
                    type="number"
                    min="1"
                    max="365"
                    value={newDays}
                    onChange={(e) => setNewDays(e.target.value)}
                    className="w-full rounded-lg border border-[hsl(var(--border))] bg-[hsl(var(--background))] px-3 py-2 text-xs text-[hsl(var(--foreground))] focus:outline-none"
                  />
                </div>
              </div>

              <div>
                <label className="block text-[11px] font-bold text-[hsl(var(--foreground))] mb-1">
                  Initial Preparation Readiness ({newProgress}%)
                </label>
                <input
                  type="range"
                  min="0"
                  max="100"
                  value={newProgress}
                  onChange={(e) => setNewProgress(e.target.value)}
                  className="w-full accent-slate-700 dark:accent-slate-300"
                />
              </div>

              <div className="flex items-center justify-end gap-2.5 pt-3 border-t border-[hsl(var(--border))]">
                <Button variant="secondary" onClick={() => setShowAddModal(false)}>
                  Cancel
                </Button>
                <Button type="submit" disabled={isAdding}>
                  {isAdding ? 'Registering...' : 'Register Deadline'}
                </Button>
              </div>
            </form>
          </div>
        </div>
      )}

      {draftMutation.isPending && (
        <div
          className="fixed bottom-5 right-5 z-20 flex items-center gap-2 rounded-lg border border-[hsl(var(--border))] bg-[hsl(var(--card))] px-4 py-3 text-[11px] font-bold shadow-lg"
          data-testid="status-drafting"
        >
          <Sparkles size={15} className="text-slate-500 animate-spin" />
          Assembling a reviewable draft…
        </div>
      )}

      {draft && (
        <Drawer title="Compliance draft · private" onClose={() => setDraft(null)}>
          <div className="flex items-start justify-between gap-3">
            <div>
              <StatusPill value={draft.status} />
              <h2 className="mt-4 gg-serif text-[26px] leading-[1.05]">{draft.title}</h2>
            </div>
            <div className="flex size-10 items-center justify-center rounded-lg bg-[hsl(var(--muted))] text-[hsl(var(--foreground))]">
              <FileText size={19} />
            </div>
          </div>

          {/* Export & Download Action Bar */}
          <div className="mt-4 flex flex-wrap items-center gap-2 rounded-lg border border-[hsl(var(--border))] bg-[hsl(var(--muted)/.4)] p-2.5">
            <span className="text-[10px] font-bold text-[hsl(var(--muted-foreground))] uppercase tracking-wider pl-1 mr-1">
              Export Report:
            </span>
            <button
              type="button"
              onClick={() => handleDownload('md')}
              className="inline-flex items-center gap-1.5 rounded-md bg-[hsl(var(--card))] border border-[hsl(var(--border))] px-3 py-1.5 text-[11px] font-bold text-[hsl(var(--foreground))] hover:bg-[hsl(var(--muted))] transition-colors shadow-2xs cursor-pointer"
              title="Download as Markdown file (.md)"
              data-testid="btn-download-md"
            >
              <Download size={13} className="text-emerald-500" />
              <span>Download .md</span>
            </button>
            <button
              type="button"
              onClick={() => handleDownload('txt')}
              className="inline-flex items-center gap-1.5 rounded-md bg-[hsl(var(--card))] border border-[hsl(var(--border))] px-3 py-1.5 text-[11px] font-bold text-[hsl(var(--foreground))] hover:bg-[hsl(var(--muted))] transition-colors shadow-2xs cursor-pointer"
              title="Download as plain text file (.txt)"
              data-testid="btn-download-txt"
            >
              <FileDown size={13} className="text-blue-500" />
              <span>Download .txt</span>
            </button>
            <button
              type="button"
              onClick={handlePrintPdf}
              className="inline-flex items-center gap-1.5 rounded-md bg-[hsl(var(--card))] border border-[hsl(var(--border))] px-3 py-1.5 text-[11px] font-bold text-[hsl(var(--foreground))] hover:bg-[hsl(var(--muted))] transition-colors shadow-2xs cursor-pointer"
              title="Print formatted report or save as PDF"
              data-testid="btn-print-pdf"
            >
              <Printer size={13} className="text-amber-500" />
              <span>Print / PDF</span>
            </button>
            <button
              type="button"
              onClick={handleCopy}
              className="inline-flex items-center gap-1.5 rounded-md bg-[hsl(var(--card))] border border-[hsl(var(--border))] px-3 py-1.5 text-[11px] font-bold text-[hsl(var(--foreground))] hover:bg-[hsl(var(--muted))] transition-colors shadow-2xs cursor-pointer sm:ml-auto"
              title="Copy report text to clipboard"
              data-testid="btn-copy-report"
            >
              {copied ? (
                <>
                  <Check size={13} className="text-emerald-500" />
                  <span className="text-emerald-500">Copied!</span>
                </>
              ) : (
                <>
                  <Copy size={13} className="text-[hsl(var(--muted-foreground))]" />
                  <span>Copy text</span>
                </>
              )}
            </button>
          </div>

          {/* Context Inputs Feeding the Drafter - subtle cards */}
          <div className="mt-5 rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--muted)/.3)] p-4 space-y-2.5">
            <div className="flex items-center justify-between">
              <span className="gg-mono text-[9px] uppercase tracking-wider font-extrabold text-[hsl(var(--foreground))]">
                Deterministic Context Inputs
              </span>
              <span className="rounded bg-[hsl(var(--muted))] px-1.5 py-0.5 font-mono text-[9px] font-bold text-[hsl(var(--muted-foreground))]">
                Article IV Enforced
              </span>
            </div>
            <div className="grid grid-cols-2 gap-2 text-[10px]">
              <div className="rounded bg-[hsl(var(--card))] border border-[hsl(var(--border))] p-2">
                <span className="text-[hsl(var(--muted-foreground))] block">Target Deadline ID:</span>
                <strong className="font-mono">#{draft.deadlineId}</strong>
              </div>
              <div className="rounded bg-[hsl(var(--card))] border border-[hsl(var(--border))] p-2">
                <span className="text-[hsl(var(--muted-foreground))] block">Preparation Readiness:</span>
                <strong className="font-mono text-[hsl(var(--foreground))]">Audit artifacts collected</strong>
              </div>
              <div className="rounded bg-[hsl(var(--card))] border border-[hsl(var(--border))] p-2">
                <span className="text-[hsl(var(--muted-foreground))] block">Safe Policy:</span>
                <strong className="text-[hsl(var(--foreground))]">Zero Autonomous Submissions</strong>
              </div>
              <div className="rounded bg-[hsl(var(--card))] border border-[hsl(var(--border))] p-2">
                <span className="text-[hsl(var(--muted-foreground))] block">PI Authority:</span>
                <strong className="text-[hsl(var(--foreground))]">Manual Signoff Required</strong>
              </div>
            </div>
          </div>

          <div
            className="mt-6 whitespace-pre-wrap border-t border-[hsl(var(--border))] pt-6 text-[12px] leading-[1.7]"
            data-testid="text-draft-body"
          >
            {draft.body}
          </div>
          <div className="mt-8 flex flex-wrap items-center justify-between gap-3 border-t border-[hsl(var(--border))] pt-4">
            <span className="text-[10px] text-[hsl(var(--muted-foreground))]">
              Review before sharing externally. Guardian never auto-submits.
            </span>
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={() => handleDownload('md')}
                className="inline-flex items-center gap-1.5 rounded-lg bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))] px-3.5 py-2 text-[11px] font-bold hover:opacity-90 transition-opacity cursor-pointer shadow-2xs"
                data-testid="btn-download-footer"
              >
                <Download size={13} />
                <span>Download Report (.md)</span>
              </button>
              <Button variant="secondary" onClick={() => setDraft(null)} testId="button-close-draft">
                Done
              </Button>
            </div>
          </div>
        </Drawer>
      )}
    </div>
  );
}